version: '3.8'

services:
  app:
    container_name: online_courses_app
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/online_courses
      # Add other environment variables here (e.g., NEXTAUTH_SECRET, etc.)
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - db

  studio:
    container_name: online_courses_studio
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npx -- prisma studio --hostname 0.0.0.0
    ports:
      - "5555:5555"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/online_courses
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: online_courses_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: online_courses
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
